name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven
      - name: Build with Maven
        run: mvn -B -DskipTests package --file pom.xml
      - name: Upload WAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: devops-tomcat-demo
          path: target/*.war

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      # 👇 This is the Azure login (OIDC) step you asked about
      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - uses: actions/download-artifact@v4
        with:
          name: devops-tomcat-demo

      - name: Deploy WAR to Azure Web App
        run: |
          WAR=$(ls *.war | head -n1)
          az webapp deploy \
            --resource-group "<YOUR_RG_NAME>" \
            --name "<YOUR_WEBAPP_NAME>" \
            --src-path "$WAR" \
            --type war \
            --async false
