name: Build WAR and Push Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: {}

permissions:
  contents: read

env:
  # EDIT THIS to the repo name you want on Docker Hub:
  # <dockerhub-username>/<image-name>
  IMAGE_REPO: sujithdocker339/devops-tomcat-demo

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: maven

      - name: Build WAR with Maven
        run: mvn -B -DskipTests package --file pom.xml

      # Compute a short tag from the commit SHA so each push is unique
      - name: Compute tags
        id: vars
        run: |
          echo "SHORT_SHA=${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build the container using the Dockerfile at repo root and push to Docker Hub
      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_REPO }}:latest
            ${{ env.IMAGE_REPO }}:${{ steps.vars.outputs.SHORT_SHA }}
